version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGO_CONNECTION=mongodb://database:27017/backend
      - SECRET=secret

    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.data:/data/db
